// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzowznzffuifkjjxbigz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6b3d6bnpmZnVpZmtqanhiaWd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4OTUzMDUsImV4cCI6MjA1NjQ3MTMwNX0.XAYccL_XxZ9pBe9PkTolxvsCR7raKTXjLEnKXHJT0PI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);